Mn/column modal
michaellee2245/group-project pull request #32
Opened 2019-02-16 20:26 UTC by mckayn10

2019-02-16 20:56 UTC, Tommydreamer57 requested changes
Looks good, just fix merge conflict

2019-02-21 02:26 UTC, mckayn10 commented
fixed conflicts

2019-02-21 06:00 UTC, huyqdang approved these changes

2019-02-22 01:25 UTC, hokakede1 commented
It has conflicts again

2019-02-22 01:28 UTC, mckayn10 commented
no longer need to merge this branch

2019-02-22 01:29 UTC, closed without merging